### ISSUE TITLE
What is the range value of EMD distance?

### ISSUE THREAD

**Issue by tornadomeet** [daerduoCarey/PyTorchEMD#1]
heelo, @daerduoCarey 

I read and test the code of EMD distance, it seems that the range value of this  distance is summed by ```n*m```, so if the n and m is too large(such as >=10000), then  EMD distance is also very large.  

should we normalize it divided by ```n*m``` if used EMD as a loss? thanks!

**Comment by daerduoCarey** [comment]
This code implements the approximate EMD so for each point in the first point cloud we compute a weighted average over all the points in the second point cloud. Refer to [1] for the algorithm details. So, in practice, you should divide the returned loss by the size of the first point cloud n, instead of n*m.

[1]: D. P. Bertsekas. A distributed asynchronous relaxation algorithm for the assignment problem. In Decision and Control, 1985 24th IEEE Conference on, pages 1703–1704. IEEE, 1985.

**Comment by tornadomeet** [comment]
got it! thanks @daerduoCarey
